!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 50
  - - clip_range
    - 0.2
  - - device
    - cuda:0
  - - ent_coef
    - 0.0
  - - gae_lambda
    - 0.95
  - - gamma
    - 0.99
  - - learning_rate
    - 0.001
  - - n_envs
    - 2
  - - n_epochs
    - 20
  - - n_steps
    - 100
  - - n_timesteps
    - 200000.0
  - - policy
    - MlpPolicy
